### ISSUE TITLE
A TransactionRequiredException is thrown when setting a Spring AsyncTaskExecutor on the LocalSessionFactoryBean

### ISSUE THREAD

**Issue by antonleliuk** [vladmihalcea/hypersistence-optimizer#110]
We are using Hibernate 5. After I add file `SessionFactoryBuilderFactory` to the `META-INF/services` I got an exception:

```
javax.persistence.TransactionRequiredException: Executing an update/delete query
	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1586)
	at org.example.hypersistence.dao.LibraryDao.deleteAll(LibraryDao.java:14)
	at org.example.hypersistence.service.LibraryService.deleteAll_aroundBody0(LibraryService.java:16)
	at org.example.hypersistence.service.LibraryService$AjcClosure1.run(LibraryService.java:1)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70)
	at org.example.hypersistence.service.LibraryService.deleteAll(LibraryService.java:16)
	at org.example.hypersistence.query.QueryTest.startup(QueryTest.java:24)
```

Methods that are using createCriteria, or createCriteriaBuilder works fine.

I created [project](https://github.com/antonleliuk/problem-hypersistence-optimizer) to reproduce a problem

**Comment by vladmihalcea** [comment]
Thanks for creating a replicating test case. I'll check it out and let you know of my findings.

**Comment by vladmihalcea** [comment]
@antonleliuk I investigated it, and here's what I found.

If you use Java-based configurations since you are using Spring 5, then everything works just fine. Here's my repository that proves it:

https://github.com/vladmihalcea/problem-hypersistence-optimizer

My testing repositories have XML-based configs as well, but they work with Spring 4 and 3. 

https://github.com/vladmihalcea/hypersistence-optimizer/

I'm sure there's some XML setting to add in order to achieve the same outcome as the Java-based config, but I couldn't figure out which one might be missing.

Are you using Spring 5 and XML configs in your current project?

**Comment by vladmihalcea** [comment]
After some additional investigations, it looks like the XML-based config uses a `Proxy` for the `SessionFactory` which overrides the `getWrappedObject` method, therefore preventing unwrapping the Hypersistence Optimizer `SessionFactory`.

I'll see how I can tackle this issue.

**Comment by vladmihalcea** [comment]
@antonleliuk I found another solution for the XML mappings which can be tested using this branch:

https://github.com/vladmihalcea/problem-hypersistence-optimizer/tree/xml-fix

Basically, you need to create this utility class:

```
public class UnproxyBean {
    public static <T> T unproxy(T bean) {
        if (bean instanceof InfrastructureProxy) {
            try {
                return (T) ((InfrastructureProxy) bean).getWrappedObject();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
        return bean;
    }
}
```

And, change your `sessionFactory` bean definition to this:

```
<bean id="originalSessionFactory" class="org.springframework.orm.hibernate5.LocalSessionFactoryBean">
	<property name="dataSource" ref="dataSource" />
	<property name="packagesToScan">
		 <list>
			 <value>org.example.hypersistence</value>
		 </list>
	</property>
	<property name="hibernateProperties">
		<props>
			<prop key="hibernate.dialect">${hibernate.dialect}</prop>
			<prop key="hibernate.hbm2ddl.auto">${hibernate.hbm2ddl.auto}</prop>
		</props>
	</property>
	<property name="bootstrapExecutor">
		<bean class="org.springframework.core.task.SimpleAsyncTaskExecutor" />
	</property>
</bean>

<bean id="sessionFactory"
	  class="org.example.hypersistence.UnproxyBean"
	  factory-method="unproxy"
	  primary="true">
	<constructor-arg ref="originalSessionFactory"/>
</bean>
```

You can use this in your test folder until I add support for this in 2.2.1.

Basically, I'll have to add this `unproxy` method to be used for the XML-based mappings when using Spring 5.
