### ISSUE TITLE
NullPointerException thrown by the isQueryFilteringByEntityId method

### ISSUE THREAD

**Issue by pkernevez** [vladmihalcea/hypersistence-optimizer#176]
Version 2.6.1

```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at io.hypersistence.optimizer.hibernate.decorator.AbstractHibernate56SessionFactoryDecorator$SessionDecorator$QueryDecorator.isQueryFilteringByEntityId(AbstractHibernate56SessionFactoryDecorator.java:1407)
	at io.hypersistence.optimizer.hibernate.decorator.AbstractHibernate56SessionFactoryDecorator$SessionDecorator$QueryDecorator.checkOrderByClause(AbstractHibernate56SessionFactoryDecorator.java:1371)
	at io.hypersistence.optimizer.hibernate.decorator.AbstractHibernate56SessionFactoryDecorator$SessionDecorator$QueryDecorator.access$2200(AbstractHibernate56SessionFactoryDecorator.java:1191)
	at io.hypersistence.optimizer.hibernate.decorator.AbstractHibernate56SessionFactoryDecorator$SessionDecorator$QueryDecorator$1.execute(AbstractHibernate56SessionFactoryDecorator.java:1322)
	at io.hypersistence.optimizer.core.action.ActionExecutor.executeThrough(ActionExecutor.java:81)
	at io.hypersistence.optimizer.hibernate.decorator.AbstractHibernate56SessionFactoryDecorator$SessionDecorator$QueryDecorator.checkBeforeQuery(AbstractHibernate56SessionFactoryDecorator.java:1319)
	at io.hypersistence.optimizer.hibernate.decorator.AbstractHibernate56SessionFactoryDecorator$SessionDecorator$QueryDecorator.getSingleResult(AbstractHibernate56SessionFactoryDecorator.java:1271)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:111)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:198)
```
This happen when calling: `repository.findFirstByFxRateBaseCurrencyAndFxRateQuoteCurrencyAndDateLessThanEqualOrderByDateDesc(CurrencyEntity1, CurrencyEntity2, LocalDate)
I don't found the source code for this class, so I can't do investigation.

**Comment by vladmihalcea** [comment]
Thanks for reporting the issue. Would you mind providing the signature for that `findFirstByFxRateBaseCurrencyAndFxRateQuoteCurrencyAndDateLessThanEqualOrderByDateDesc` method?

I want to see what it returns so that I can figure out the problem.

**Comment by pkernevez** [comment]
Yes it's:
``` java
   Optional<CurrencyExchangeRateHistoryEntity> findFirstByFxRateBaseCurrencyAndFxRateQuoteCurrencyAndDateLessThanEqualOrderByDateDesc(
            CurrencyEntity baseCurrency,
            CurrencyEntity quoteCurrency,
            LocalDate date);
```

**Comment by vladmihalcea** [comment]
Thanks. I'll try to replicate it.

**Comment by vladmihalcea** [comment]
@pkernevez I have a few questions. 

1. Is the `CurrencyExchangeRateHistoryEntity` mapped as an entity, right?
2. Are these properties mapped as regular entity attributes: `fxRateBaseCurrency`, `fxRateQuoteCurrency`, and `date`?

Or, are they derived using `@Formula` or something like that?

**Comment by pkernevez** [comment]
I've question about hibernate behavior and I'm preparing a simple project for the forum, I will try to reproduce this behavior in it then share it here.

**Comment by vladmihalcea** [comment]
Thanks. In the meantime, I'll add some extra checks for this as I could replicate something similar with a composite id.

**Comment by s-jepsen** [comment]
Got a similar issue.

**Comment by vladmihalcea** [comment]
@s-jepsen The fix is in the making. I'll release a new patch version next week.

**Comment by pkernevez** [comment]
Do you still need additional information ?

**Comment by vladmihalcea** [comment]
@pkernevez It's fine at the moment. I'll let you know when the release is ready so that you can test it. I'm now working on fixing it for all verisons.

**Comment by vladmihalcea** [comment]
Fixed.
