### ISSUE TITLE
NullPointerException is thrown when scanning a composite entity identifier

### ISSUE THREAD

**Issue by thunderhook** [vladmihalcea/hypersistence-optimizer#2]
When using `1.0.1-SNAPSHOT` on one of our projects we get the following error:

	10:47:12.159 ERROR Hypersistence Optimizer - The [io.hypersistence.optimizer.hibernate.scanner.Hibernate53MappingScanner$4] encountered a problem when calling the [execute] method.
	java.lang.NullPointerException: null
		at io.hypersistence.optimizer.hibernate.scanner.Hibernate53MappingScanner$4.execute(Hibernate53MappingScanner.java:203)
		at io.hypersistence.optimizer.core.action.ActionExecutor.execute(ActionExecutor.java:70)
		at io.hypersistence.optimizer.hibernate.scanner.Hibernate53MappingScanner.scanEntityIdentifier(Hibernate53MappingScanner.java:171)
		at io.hypersistence.optimizer.hibernate.scanner.Hibernate53MappingScanner.access$200(Hibernate53MappingScanner.java:76)
		at io.hypersistence.optimizer.hibernate.scanner.Hibernate53MappingScanner$1.execute(Hibernate53MappingScanner.java:100)
		at io.hypersistence.optimizer.core.action.ActionExecutor.execute(ActionExecutor.java:70)
		at io.hypersistence.optimizer.hibernate.scanner.Hibernate53MappingScanner.scan(Hibernate53MappingScanner.java:90)
		at io.hypersistence.optimizer.HypersistenceOptimizer.init(HypersistenceOptimizer.java:74)
		at our.test.HypersistenceOptimizerTest.testOptimizer(HypersistenceOptimizerTest.java:42)

This happens between some events, so it does not stop the optimizer, but it seems this swallows some possible events.

**Comment by vladmihalcea** [comment]
Thanks for the info. I will need a replicating test case to debug your use case.

You are right that the exceptions are handled and don't stop the processing because the framework is designed to avoid impacting your application bootstrap, so it works taking a best effort approach.

You can use the `hibernate-oprimizer-test-case` module to provide your use case. Looking forward to it.

**Comment by thunderhook** [comment]
OK i narrowed down my problem. It is an entity which is only used to project a view (of multiple joins). Interestingly I used multiple `@Id` annotations. An entity like below is causing the stack trace. I hope you don't mind when I don't provide a test-case, I have too little time and wanted to respond quickly.

```
@Entity
@Immutable
@Table(name = "some_view")
public class SomeViewEntry implements Serializable {

	@Id
	@Column(name = "main_id")
	private Long mainId;

	@Column(name = "some_field")
	private LocalDate someField;

	@Id
	@Column(name = "another_id")
	private Long anotherId;

	@Column(name = "another_field")
	private String anotherField;

	public Long getMainId() {
		return mainId;
	}

	public LocalDate getSomeField() {
		return someField;
	}

	public Long getAnotherId() {
		return anotherId;
	}

	public String getAnotherField() {
		return anotherField;
	}
}
```

**Comment by vladmihalcea** [comment]
Thanks for taking your time for the entity class. I'll write the test case myself.

**Comment by vladmihalcea** [comment]
Fixed.
