### ISSUE TITLE
ClassCastException: class sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to class java.lang.Class

### ISSUE THREAD

**Issue by pergravgaard** [vladmihalcea/hypersistence-optimizer#250]
The stack trace error:

````
java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.TypeVariableImpl and java.lang.Class are in module java.base of loader 'bootstrap')
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate63MappingScanner$4.execute(Hibernate63MappingScanner.java:247) ~[hypersistence-optimizer-2.9.0-jakarta.jar:?]
	at io.hypersistence.optimizer.core.action.ActionExecutor.execute(ActionExecutor.java:68) ~[hypersistence-optimizer-2.9.0-jakarta.jar:?]
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate63MappingScanner.scanBasicIdentifierGenerator(Hibernate63MappingScanner.java:203) ~[hypersistence-optimizer-2.9.0-jakarta.jar:?]
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate63MappingScanner.scanEntityIdentifier(Hibernate63MappingScanner.java:188) ~[hypersistence-optimizer-2.9.0-jakarta.jar:?]
````

The method that is failing is `scanCompositeIdentifierGenerator`.

The problem seems to be caused by the following mapping:

````
@MappedSuperclass
public abstract class AbstractEntity<ID extends Serializable> implements Persistable<ID> {

    @Id
    @GeneratedValue(
            strategy = GenerationType.AUTO
    )
    @Column(nullable = false, unique = true, updatable = false)
    private ID id;
...
}
````

**Comment by vladmihalcea** [comment]
@pergravgaard I will need the entity mapping that triggers this issue. Since the `scanCompositeIdentifierGenerator` method failed, it means the entity mapping i using some composite identifier, which I will need in order to replicate the problem.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by pergravgaard** [comment]
Thank you very much. That' was quick.

:-) Per

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by vladmihalcea** [comment]
@pergravgaard You're welcome. Let me know if the 2.10.1 version fixes the problem.
