### ISSUE TITLE
Add Support for Spring Boot 3

### ISSUE THREAD

**Issue by derkent** [vladmihalcea/hypersistence-optimizer#251]
If I understand it correctly, there is support for Hibernate 6 but not yet, support for SpringBoot 3. 

Support for Spring Boot 3 and all of the jakarta related classes would be an enable me to use the optimizer.

**Comment by vladmihalcea** [comment]
You need to use the `jakarta` classifier, as explained in the [documentation](https://vladmihalcea.com/hypersistence-optimizer/docs/installation-guide/#Jakarta_Persistence).

**Comment by derkent** [comment]
I looked there first, and the code examples. However I get class not found exceptions.
This 
`
 @Bean
  public HypersistenceOptimizer hypersistenceOptimizer() {
    return new HypersistenceOptimizer(new HibernateConfig(getSessionFactory()));
  }`
results in

Caused by: java.lang.ClassNotFoundException: javax.persistence.EntityManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)

Caused by: java.lang.NoClassDefFoundError: javax/persistence/EntityManager
	at io.hypersistence.optimizer.hibernate.decorator.Hibernate56SessionFactoryBuilderFactory$SessionFactoryDecoratorBuilder.build(Hibernate56SessionFactoryBuilderFactory.java:90)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1506)

and  
`  @Bean
  public HypersistenceOptimizer hypersistenceOptimizer(EntityManagerFactory entityManagerFactory) {
    return new HypersistenceOptimizer(new JpaConfig(null));
  }`

Looks hopeless because JpaConfig expects javax.persistence.EntityManagerFactory

**Comment by vladmihalcea** [comment]
Spring Boot 3 does not use Hibernate 5.6, and your error shows that the `Hibernate56SessionFactoryBuilderFactory` was used, so there is a problem with your dependency configuration.

Here's a [Git Hub project](https://github.com/vladmihalcea/hypersistence-optimizer/tree/master/hypersistence-optimizer-spring-boot3-example) that uses Spring Boot 3 with the Optimizer enabled. You need to compare your dependency config to this project and see where they differ.
