### ISSUE TITLE
NullPointerException: null at Hibernate52MappingScanner

### ISSUE THREAD

**Issue by neerajjain92** [vladmihalcea/hypersistence-optimizer#3]
After providing some analysis of MINOR and CRITICAL problems, the optimizer ends up throwing the following error.

```
java.lang.NullPointerException: null
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate52MappingScanner$4.execute(Hibernate52MappingScanner.java:203) ~[hypersistence-optimizer-1.0.1-SNAPSHOT.jar:na]
	at io.hypersistence.optimizer.core.action.ActionExecutor.execute(ActionExecutor.java:70) [hypersistence-optimizer-1.0.1-SNAPSHOT.jar:na]
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate52MappingScanner.scanEntityIdentifier(Hibernate52MappingScanner.java:171) [hypersistence-optimizer-1.0.1-SNAPSHOT.jar:na]
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate52MappingScanner.access$200(Hibernate52MappingScanner.java:76) [hypersistence-optimizer-1.0.1-SNAPSHOT.jar:na]
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate52MappingScanner$1.execute(Hibernate52MappingScanner.java:100) [hypersistence-optimizer-1.0.1-SNAPSHOT.jar:na]
	at io.hypersistence.optimizer.core.action.ActionExecutor.execute(ActionExecutor.java:70) [hypersistence-optimizer-1.0.1-SNAPSHOT.jar:na]
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate52MappingScanner.scan(Hibernate52MappingScanner.java:90) [hypersistence-optimizer-1.0.1-SNAPSHOT.jar:na]
	at io.hypersistence.optimizer.HypersistenceOptimizer.init(HypersistenceOptimizer.java:74) [hypersistence-optimizer-1.0.1-SNAPSHOT.jar:na]
```

**Comment by vladmihalcea** [comment]
Thanks for the info. I will need a replicating test case to debug your use case.

You can use the `hibernate-oprimizer-test-case` module to provide your use case. Looking forward to it.

**Comment by vladmihalcea** [comment]
@neerajjain92 Any chance you provide the entity mapping that caused this issue? Otherwise, I won't be able to fix it.
