### ISSUE TITLE
License cannot be loaded in an OSGi container

### ISSUE THREAD

**Issue by VanAuer** [vladmihalcea/hypersistence-optimizer#34]
While optimizer startup process (trial version) there occurs the following error:

```
org.apache.karaf.features.internal.util.MultiException: Error restarting bundles:
Activator start error in bundle my-bundle [57].
at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1004)
at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1025)
at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:964)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Suppressed: org.osgi.framework.BundleException: Activator start error in bundle my-bundle [57].
		at org.apache.felix.framework.Felix.activateBundle(Felix.java:2290)
		at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
		at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
		at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
		at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:161)
		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1116)
		at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:996)
		... 6 more
Caused by: java.lang.ExceptionInInitializerError
		at io.hypersistence.optimizer.core.License.getProperties(License.java:135)
		at io.hypersistence.optimizer.core.License.isTrialVersion(License.java:110)
		at io.hypersistence.optimizer.HypersistenceOptimizer.printBanner(HypersistenceOptimizer.java:104)
		at io.hypersistence.optimizer.HypersistenceOptimizer.init(HypersistenceOptimizer.java:72)
		at MyApplication.start(MyApplication.java:493)
		at MyApplication.startApplication(ApplicationLauncher.java:116)
		at MyApplication.launch(ApplicationLauncher.java:45)
		at Activator.start(Activator.java:47)
		at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
		at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
		... 12 more
Caused by: java.lang.NullPointerException
		at io.hypersistence.optimizer.util.FileUtils.readBytesFromStream(FileUtils.java:95)
		at io.hypersistence.optimizer.core.License$LicenseKey.<clinit>(License.java:72)
		... 22 more

```
The optimizer jar is embedded in an OSGi bundle who's running in a Karaf container. It seems that the application can not find the license file who's inside the embedded jar. Wrapping the optimizer jar to a stand-alone bundle is also not working.

**Comment by vladmihalcea** [comment]
In order to investigate it, I need you to send me a Pull Request with a module that uses Felix, Karaf and demonstrates the issue. I haven't used OSGI, so I'm not very familiar with it, and having a replicating module will surely help me investigate this issue.

Meanwhile, you can use Hypersistence Optimizer for integration testing, where you shouldn't need an OSGI container.

**Comment by vladmihalcea** [comment]
With the version 1.2.2, you can now set an external license file, [as explained in the User Guide](https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/#Using_an_external_Hypersistence_Optimizer_license_file).

This can be used in managed environments like OSGI. You just need to provide the right URL that your environment allows you to access from Java.
