### ISSUE TITLE
ConfigurationScanner propagates database connectivity issues and stops the bootstrap process

### ISSUE THREAD

**Issue by rroschin** [vladmihalcea/hypersistence-optimizer#43]
No test case is provided due to complexity of a project. This is happened when Hypersistence Optimizer was integrated into an existing project (with many-many-many hibernate problems).
This is the init code:
`new HypersistenceOptimizer(new HibernateConfig(sf)).init();`

And this is the error happened during the start: 
```
ERROR Hypersistence Optimizer - The [org.hibernate.engine.jdbc.connections.spi.AbstractMultiTenantConnectionProvider] encountered a problem when calling the [supportsAggressiveRelease] method.
java.lang.NullPointerException: null
	at org.hibernate.engine.jdbc.connections.spi.AbstractMultiTenantConnectionProvider.supportsAggressiveRelease(AbstractMultiTenantConnectionProvider.java:63) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.AbstractSessionImpl$ContextualJdbcConnectionAccess.supportsAggressiveRelease(AbstractSessionImpl.java:447) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.determineConnectionReleaseMode(LogicalConnectionImpl.java:126) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.<init>(LogicalConnectionImpl.java:108) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.<init>(LogicalConnectionImpl.java:87) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.<init>(JdbcCoordinatorImpl.java:114) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionCoordinatorImpl.<init>(TransactionCoordinatorImpl.java:89) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.SessionImpl.<init>(SessionImpl.java:258) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl.openSession(SessionFactoryImpl.java:1589) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.SessionFactoryImpl.openTemporarySession(SessionFactoryImpl.java:1003) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate43ConfigurationScanner$DatabaseMetadataContext.<init>(Hibernate43ConfigurationScanner.java:386) ~[hypersistence-optimizer-1.2.0-SNAPSHOT.jar:?]
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate43ConfigurationScanner.<init>(Hibernate43ConfigurationScanner.java:87) ~[hypersistence-optimizer-1.2.0-SNAPSHOT.jar:?]
	at io.hypersistence.optimizer.hibernate.Hibernate43Service.getScanners(Hibernate43Service.java:47) ~[hypersistence-optimizer-1.2.0-SNAPSHOT.jar:?]
	at io.hypersistence.optimizer.core.service.DefaultService.getHibernateScanners(DefaultService.java:73) ~[hypersistence-optimizer-1.2.0-SNAPSHOT.jar:?]
	at io.hypersistence.optimizer.core.service.DefaultService.getScanners(DefaultService.java:54) ~[hypersistence-optimizer-1.2.0-SNAPSHOT.jar:?]
	at io.hypersistence.optimizer.HypersistenceOptimizer.init(HypersistenceOptimizer.java:73) ~[hypersistence-optimizer-1.2.0-SNAPSHOT.jar:?]
```

Best of luck, we were not able to try this tool because of the issue.

**Comment by vladmihalcea** [comment]
Thanks for filling the issue. I'll debug it and try to figure it out.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by vladmihalcea** [comment]
@rroschin You can test the [latest Trial Version](https://store.vladmihalcea.com/p/hypersistence-optimizer-trial). This issue should be fixed now.
