### ISSUE TITLE
Prevent a NullPointerException in the ConfigurationScanner if the ConnectionProvider cannot be located

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hypersistence-optimizer#80]
A NullPoiterException can be thrown if the `ConnectionProvider` cannot be located.

```
The [io.hypersistence.optimizer.hibernate.scanner.Hibernate53ConfigurationScanner$1] encountered a problem when calling the [execute] method.
java.lang.NullPointerException: null
at io.hypersistence.optimizer.hibernate.scanner.Hibernate53ConfigurationScanner$1.execute(Hibernate53ConfigurationScanner.java:122) ~[hypersistence-optimizer-2.0.0.jar:?]
at io.hypersistence.optimizer.core.action.ActionExecutor.execute(ActionExecutor.java:69) ~[hypersistence-optimizer-2.0.0.jar:?]
at io.hypersistence.optimizer.hibernate.scanner.Hibernate53ConfigurationScanner.scanConnectionProvider(Hibernate53ConfigurationScanner.java:114) ~[hypersistence-optimizer-2.0.0.jar:?]
at io.hypersistence.optimizer.hibernate.scanner.Hibernate53ConfigurationScanner.scan(Hibernate53ConfigurationScanner.java:104) ~[hypersistence-optimizer-2.0.0.jar:?]
```

**Comment by vladmihalcea** [comment]
Fixed.
