### ISSUE TITLE
A "could not resolve the suggested Dialect" exception is thrown when using Quarkus

### ISSUE THREAD

**Issue by apderosso** [vladmihalcea/hypersistence-optimizer#92]
I'm running the Hypersistence Optimizer using Quarkus and I'm getting the following:

```
2020-03-16 11:16:21,786 WARN  [Hypersistence Optimizer] (main) Could not resolve the suggested Dialect. Some database checks will be disabled.: org.hibernate.service.UnknownServiceException: Unknown service requested [org.hibernate.engine.jdbc.dialect.spi.DialectFactory]
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate54ConfigurationScanner.getSuggestedDialect(Hibernate54ConfigurationScanner.java:176)
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate54ConfigurationScanner.access$100(Hibernate54ConfigurationScanner.java:85)
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate54ConfigurationScanner$2.execute(Hibernate54ConfigurationScanner.java:144)
	at io.hypersistence.optimizer.core.action.ActionExecutor.execute(ActionExecutor.java:69)
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate54ConfigurationScanner.scanDialect(Hibernate54ConfigurationScanner.java:141)
	at io.hypersistence.optimizer.hibernate.scanner.Hibernate54ConfigurationScanner.scan(Hibernate54ConfigurationScanner.java:107)
	at io.hypersistence.optimizer.HypersistenceOptimizer.<init>(HypersistenceOptimizer.java:69)
	at com.assaabloy.pbs.api.HypersistenceOptimzerTest.test(HypersistenceOptimzerTest.java:30)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:127)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
```

My persistence.xml looks like:

```
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence
             http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd"
             version="2.1">
    <persistence-unit name="PBS" transaction-type="JTA">
        <properties>
            <!-- Connection specific -->
            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL57Dialect"/>
            <property name="hibernate.jdbc.batch_size" value="30"/>
            <property name="hibernate.order_inserts" value="true"/>
            <property name="hibernate.query.fail_on_pagination_over_collection_fetch" value="true"/>
            <property name="hibernate.query.in_clause_parameter_padding" value="true"/>
            <property name="hibernate.connection.handling_mode" value="delayed_acquisition_and_release_after_transaction"/>
            <property name="hibernate.show_sql" value="false"/>
            <property name="hibernate.format_sql" value="false"/>
        </properties>
    </persistence-unit>
</persistence>
```

**Comment by vladmihalcea** [comment]
That issue will not prevent the scanning process from continuing. It's just that some checks cannot be done because, for some reason, that service is not available.

I haven't tested Hypersistence Optimizer with Quarkus yet, but if that's the only issue you found, I guess it's a great start.

**Comment by apderosso** [comment]
Right, not an issue, just wanted to bring it up. And yes, working in Quarkus just fine 😄 

Excellent project by the way!

**Comment by vladmihalcea** [comment]
I'm glad to hear that. I will investigate it once I have some time. Stay tuned for more awesome checks.

**Comment by vladmihalcea** [comment]
Fixed.
