### ISSUE TITLE
Add a Java 6 shaded dependency for projects still using Java 6

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hypersistence-optimizer#98]
On legacy Java EE application servers, like JBoss 5, when the default `hypersistence-optimizer` dependency is scanned, the application server can throw the following `DeploymentException`:

```
org.jboss.deployers.spi.DeploymentException: Error deploying xxxxx.ear: invalid constant type: 18
        at org.jboss.ejb3.deployers.Ejb3Deployer.deploy(Ejb3Deployer.java:196)
        at org.jboss.ejb3.deployers.Ejb3Deployer.deploy(Ejb3Deployer.java:99)
...
Caused by: java.io.IOException: invalid constant type: 18
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1027)
        at javassist.bytecode.ConstPool.read(ConstPool.java:970)
```

Because the shaded `hypersistence-optimizer` contains both Java 6-specific classes (Hibernate ORM 
5.0, 4.3, 4.2, 4.1, 3.6, 3.5, 3.3) and Java-8-specific classes (Hibernate ORM 5.4, 5.3, 5.2, 5.1), the Javassist library stumbles on Java 8 classes and cannot proceed further.

For this reason, a Java-6 only dependency should be added to the project package.

**Comment by vladmihalcea** [comment]
Fixed.
